### ISSUE TITLE
Final Report

### ISSUE THREAD

**Issue by Lazar-source** [Teaching-projects/SZE-MOSZE-2020-Daemons#25]
Elkészültünk a report-al és a videók is fel vannak töltve.

**Comment by hegyhati** [comment]
Egyelore meg csak atfutok az md-knek a feedback reszen, erre reagalva kerdeznem: neptunban Ti nem latjatok, hogy mirol fog szolni a targy, illetve a tavalyi targy linkjet (https://github.com/hegyhati/T4MSD/wiki) nem kuldtem el felev elejen? Par dolog meg a sorrend valtozott, de a java az ugyanaz.

**Comment by Lazar-source** [comment]
Itt amit én írtam nem feltétlenül a használt technológiák és azoknak a sorrendje, hanem amit én szívesen láttam volna az a játék fejlesztési folyamat (a játék hogyan fog haladni, először 2 unit üti egymást, aztán lesz Hero, Monster stb) egy amolyan szép Barokki körmondatban.
Ez persze egyéni vélemény, próbáltam visszajelzést adni, mást nem találtam amit esetleg hiányoltam volna/ bele lehetett volna kötni.

**Comment by hegyhati** [comment]
Ach, hogy azt a reszet, ertem! Ez iden nem is volt meg teljesen elore (tavaly kb igen). De ha meglett volna, akkor sem adtam volna ki. Ha az ember latja elore, hogy ez meg ez lesz madj, akkor eleve ugy tervezi meg a dolgait. Ezt direkt akartuk/akartam elkerulni, es "kieroszaakolni" azt, hogy elindult a dolog valamilyen iranyba, nem arra megy, atirni, refaktoralni, stb. Kicsit szimulalni azt, hogy sokszor ceges kornyezetben sem egyertelmu, vagy tudni, hogy 2 honap mulva mit kell majd beletenni a szoftverbe. Koszi a feedbacket!

**Comment by Lazar-source** [comment]
Ohh értem, így már világos miért alakult így. Köszönöm a részletes választ, meg hogy érdekelt a feedback!

**Comment by Lazar-source** [comment]
@hegyhati  Máté, azt irtad a discussionsbe, hogy minden csapat értékelve lett, viszont szerintem mi kimaradtunk ebből a körből, elvileg mindent jól csináltunk.
Rá tudsz még nézni nekünk a csoportos feladatunkra? Ha nem muszáj nem készülnénk egyénileg a vizsgára.

**Comment by hegyhati** [comment]
hm... Ti vagytok a 3. csapat, amelyik valahogy kimaradt. nem tudom, mi tortent, garantaltan az en saram, meg fogom meg nezni ma este.

**Comment by Lazar-source** [comment]
Semmi baj, várjuk az értékelést!

**Comment by hegyhati** [comment]
Most nem volt vilagos, hogy az SVG akkor meglett, vagy nem, mert a listaban nincs ott, de a skilleknel meg ott van. Mindensetre amugy rendben van a dolog, jo lett volna ha ez meg megvan, de jar az otos mindenkinek.

**Comment by Lazar-source** [comment]
Jajj, bocsánat, az nem tűnt fel senkinek hogy kimaradt a felsorolásból, de meglett az is. Köszönjük!
